- name: ensure nginx is at the latest version
  apt: name=nginx state=latest update_cache=yes
  register: result
  ignore_errors: yes
  until: result is not failed
  retries: 6
  delay: 5
- name: remove symlink
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent
- name: basic config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
